DELETE http://localhost:3003/api/blogs/66c227f9b0e3be469251dc11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdlcmFyZHdheSIsImlkIjoiNjZjMjI1ODI0YTllZDIwYWRkODc3YTI0IiwiaWF0IjoxNzIzOTk5NjUzLCJleHAiOjE3MjQwMDMyNTN9.AONKqzH8qI-jo3mOOXk_4CNUrnxeH3J42UK-xXaJcrs

